version: '3.9'

services:
  # main app config
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
      - redis
      - kafka
  db:
    container_name: tascaling_postgres
    image: postgres:17-alpine
    ports:
      - 5440:5432
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "tascaling_db"
      POSTGRES_USER: "postgres"
    volumes:
      - .postgres:/var/lib/postgresql/data

  # redis-cache docker config
  redis:
    container_name: tascaling_redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    command: ["redis-server"]
    restart: always

  # kafka docker config
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://${KAFKA_OUTSIDE_HOST}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  
